### ISSUE TITLE
BigEndianReader.ReadBytes and FillReadBuffer is broken

### ISSUE THREAD

**Issue by MikeRosoft** [angelobreuer/BufferIO#1]
The `ReadBytes` function is implemented as the following:

```
        public void ReadBytes(byte[] buffer, int offset, int count)
        {
            if (BaseStream.Read(buffer, offset, count) < 0)
            {
                throw new EndOfStreamException();
            }
        }
```

`Stream.Read(buffer, offset, count)` does not return a negative value. It can return less bytes than expected (if that many bytes is not available at the moment), or 0 at the end of stream. (If *not* at the end of stream, then the function will wait until at least one character is read. For example: if the stream is a pipe and no bytes are available, then reading will hang until the writer either closes the stream, or writes at least one byte.) So the result is that the function may silently fill the array with less bytes than expected, and give no indication that this is what has happened.

In addition, the non-public `FillReadBuffer` function is implemented incorrectly. Again, `Stream.Read` may return less bytes than expected; this is normal and doesn't necessarily mean that the end of stream has been reached.

Contrast this - e.g. using ILSpy utility - with the implementation of .NET `BinaryReader`, where `ReadBytes` returns the array instead of filling it, and both `ReadBytes` and the typed `Read` functions (using non-public function `FillBuffer`) repeatedly call `Stream.Read` if necessary.

**Comment by angelobreuer** [comment]
-- @MikeRosoft 
Thanks for your issue!

> Stream.Read(buffer, offset, count) does not return a negative value. It can return less bytes than expected (if that many bytes is not available at the moment), or 0 at the end of stream. (If not at the end of stream, then the function will wait until at least one character is read. For example: if the stream is a pipe and no bytes are available, then reading will hang until the writer either closes the stream, or writes at least one byte.) So the result is that the function may silently fill the array with less bytes than expected, and give no indication that this is what has happened.

> In addition, the non-public FillReadBuffer function is implemented incorrectly. Again, Stream.Read may return less bytes than expected; this is normal and doesn't necessarily mean that the end of stream has been reached.

I will come up with a PR because I wanted to upgrade the library to the new `Span` struct introduced in .NET Standard 2.1. I did not have the time recently, but I will include a fix for this issue while I'm at it. 

> Contrast this - e.g. using ILSpy utility - with the implementation of .NET BinaryReader, where ReadBytes returns the array instead of filling it, and both ReadBytes and the typed Read functions (using non-public function FillBuffer) repeatedly call Stream.Read if necessary.

Assuming you mean the following: https://github.com/dotnet/runtime/blob/64da821c7b3e60f9aeaf2c3d544d33d19e2fc82e/src/libraries/System.Private.CoreLib/src/System/IO/BinaryReader.cs#L481

As far as I remember, it was not my intention to provide a similar interface to the BinaryReader/-Writer types, and as this is a breaking-change, I think I would like to leave it as it is.

Angelo Breuer

**Comment by angelobreuer** [comment]
I've merged the PR containing the fix now, please let me know if you have any issues regarding the PR.
I will publish the updated package on NuGet soon.
